/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestordecitas.pantallas;

import entidades.Cita;
import entidades.Especialidad;
import entidades.Medico;
import entidades.Paciente;
import gestordecitass.GestorDeCitas;

/**
 *
 * @author Estudiante
 */
public class JFrameCita extends javax.swing.JFrame {

    //El formulario padre 
    private JFrameGestorDeCitas padre;
    private Cita cita;
    private boolean Editando = false;
    private Medico medicoSeleccionado;
    private Paciente pacienteSeleccionado;
    private Especialidad especialidadSeleccionada;
    /**
     * Creates new form JFramCitas
     * @param padre
     */
    public JFrameCita(JFrameGestorDeCitas padre) {
        initComponents();
        this.padre=padre;
        
        cbxEspecialidadCrear.removeAllItems();
        cbxEspecialidadCrear.setEnabled(false);
        
        cmbHoraCrear.removeAllItems();
        GestorDeCitas.HorasDisponibles.forEach((hora) -> {
            cmbHoraCrear.addItem(hora);
        });
        cmbFechaCrear.removeAllItems();
        GestorDeCitas.FechasDisponibles.forEach((fecha) -> {
            cmbFechaCrear.addItem(fecha);
        });
        
        
        
    }
    public JFrameCita(JFrameGestorDeCitas padre,Cita cita) {
        initComponents();
        this.padre=padre;
        this.cita=cita;
        this.Editando=true;
        this.btnBuscarPaciente.setVisible(false);
        this.btnBuscarMedico.setVisible(false);
        this.btnCrearCita.setVisible(false);
        lblTitulo.setText("Visualizar Cita");
        this.txtMedicoCrear.setText(cita.getMedico().getDatosMostrar());
        this.txtPacienteCrear.setText(cita.getPaciente().getDatosMostrar());
        cbxEspecialidadCrear.removeAllItems();
        cbxEspecialidadCrear.addItem(cita.getEspecialidad().getNombre());
        
        cmbFechaCrear.removeAllItems();
        cmbFechaCrear.addItem(GestorDeCitas.FechasDisponibles.get(cita.getFecha()));
        
        cmbHoraCrear.removeAllItems();
        cmbHoraCrear.addItem(GestorDeCitas.FechasDisponibles.get(cita.getHora()));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPacienteCrear = new javax.swing.JTextField();
        txtMedicoCrear = new javax.swing.JTextField();
        btnBuscarPaciente = new javax.swing.JButton();
        btnBuscarMedico = new javax.swing.JButton();
        cbxEspecialidadCrear = new javax.swing.JComboBox<>();
        cmbFechaCrear = new javax.swing.JComboBox<>();
        cmbHoraCrear = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnCrearCita = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscarPaciente.setBackground(new java.awt.Color(0, 0, 255));
        btnBuscarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPaciente.setText("Buscar Paciente");
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });

        btnBuscarMedico.setBackground(new java.awt.Color(0, 0, 255));
        btnBuscarMedico.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarMedico.setText("Buscar Medico");
        btnBuscarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMedicoActionPerformed(evt);
            }
        });

        cbxEspecialidadCrear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxEspecialidadCrear.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbxEspecialidadCrearPropertyChange(evt);
            }
        });

        cmbFechaCrear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbHoraCrear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setText("Salir");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCrearCita.setBackground(new java.awt.Color(51, 204, 0));
        btnCrearCita.setText("Guardar");
        btnCrearCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCitaActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("Nueva Cita");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbxEspecialidadCrear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMedicoCrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                .addComponent(txtPacienteCrear, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cmbFechaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbHoraCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCrearCita, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPacienteCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarMedico, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtMedicoCrear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxEspecialidadCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbHoraCrear)
                    .addComponent(cmbFechaCrear))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearCita, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMedicoActionPerformed
        // TODO add your handling code here:
        
        JFrameMedicos pantallaMedicos=new JFrameMedicos(this);
        pantallaMedicos.setLocationRelativeTo(this);
        pantallaMedicos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBuscarMedicoActionPerformed

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
        // TODO add your handling code here:
        JFramePacientes pantallaPacientes=new JFramePacientes(this);
        pantallaPacientes.setLocationRelativeTo(this);
        pantallaPacientes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    public void guardarCita(){
        
        
        if(medicoSeleccionado!=null &&pacienteSeleccionado!=null&&especialidadSeleccionada!=null){
            cita = new Cita(medicoSeleccionado,pacienteSeleccionado,especialidadSeleccionada);
            this.padre.agregarCita(cita);
        }
        
        
        
    }
    
    public void setPaciente(Paciente paciente){
        this.pacienteSeleccionado=paciente;
        txtPacienteCrear.setText(paciente.getDatosMostrar());
    }
    public void setMedico(Medico medico){
        this.medicoSeleccionado=medico;
        
        cbxEspecialidadCrear.removeAllItems();
        for(Especialidad espec : medico.getEspecialidades()){
            cbxEspecialidadCrear.addItem(espec.getNombre());
        }
        cbxEspecialidadCrear.setEnabled(true);
        
        
    }
    public void setEspecialidad(Especialidad especialidad ){
        this.especialidadSeleccionada=especialidad;
    }
    
    private void btnCrearCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCitaActionPerformed
        // TODO add your handling code here:
        guardarCita();
        salir();
    }//GEN-LAST:event_btnCrearCitaActionPerformed

    private void cbxEspecialidadCrearPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbxEspecialidadCrearPropertyChange
        // TODO add your handling code here:
        if(this.medicoSeleccionado!=null){
            Especialidad Espec =this.medicoSeleccionado.getEspecialidades().get(cbxEspecialidadCrear.getSelectedIndex());
        setEspecialidad(Espec);
        }
        
    }//GEN-LAST:event_cbxEspecialidadCrearPropertyChange

    /**
     * Debe abrir la ventana Paciente y 
     * permitirme escoger un paciente
     */
    private void buscarPaciente(){
        JFramePacientes paciente = new JFramePacientes(this);
        paciente.setLocationRelativeTo(null);
        paciente.setVisible(true);
    }
    
    private void salir(){
        //Muestra la ventana padre
        padre.setVisible(true);
        //Elmina esta ventana para no ocupar memoria
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameCita(new JFrameGestorDeCitas()).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMedico;
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearCita;
    private javax.swing.JComboBox<String> cbxEspecialidadCrear;
    private javax.swing.JComboBox<String> cmbFechaCrear;
    private javax.swing.JComboBox<String> cmbHoraCrear;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtMedicoCrear;
    private javax.swing.JTextField txtPacienteCrear;
    // End of variables declaration//GEN-END:variables
}
